export enum StickerType {
  GAME = 'game',
  SELECT = 'select',
  CONTAINER = 'container',
  SELECT_CENTER = 'select-center',
  MENU = 'menu',
  ITEM = 'item',
  FILE = 'file',
  OPERATION = 'operation',
  LOG = 'log',
  LINK = 'link',
  WINETRICKS = 'winetricks',
  IMAGE = 'image',
  RUNTIME = 'runtime',
  LAYER = 'layer',
}